In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
import seaborn as sns

In [ ]:
pd.set_option('display.max_columns', None)

In [5]:
companies = pd.read_csv("Unicorn_Companies.csv")
companies.head()

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors
0,Bytedance,$180B,4/7/17,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S..."
1,SpaceX,$100B,12/1/12,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,SHEIN,$100B,7/3/18,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China..."
3,Stripe,$95B,1/23/14,Fintech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG"
4,Klarna,$46B,12/12/11,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita..."

In [6]:
companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1074 entries, 0 to 1073
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1074 non-null   object
 1   Valuation         1074 non-null   object
 2   Date Joined       1074 non-null   object
 3   Industry          1074 non-null   object
 4   City              1058 non-null   object
 5   Country/Region    1074 non-null   object
 6   Continent         1074 non-null   object
 7   Year Founded      1074 non-null   int64
 8   Funding           1074 non-null   object
 9   Select Investors  1073 non-null   object
dtypes: int64(1), object(9)
memory usage: 84.0+ KB

In [7]:
companies.dtypes

Company             object
Valuation           object
Date Joined         object
Industry            object
City                object
Country/Region      object
Continent           object
Year Founded         int64
Funding             object
Select Investors    object
dtype: object

In [13]:
companies['Date Joined'] = pd.to_datetime(companies["Date Joined"])
companies.dtypes

C:\Users\Adewole\AppData\Local\Temp\ipykernel_17940\3967289396.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  companies['Date Joined'] = pd.to_datetime(companies["Date Joined"])

Company                     object
Valuation                   object
Date Joined         datetime64[ns]
Industry                    object
City                        object
Country/Region              object
Continent                   object
Year Founded                 int64
Funding                     object
Select Investors            object
dtype: object

In [14]:
companies["Year Joined"] = companies["Date Joined"].dt.year
companies['Years to Unicorn'] = companies["Year Joined"] - companies["Year Founded"]
companies.head()

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Year Joined,Years to Unicorn
0,Bytedance,$180B,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S...",2017,5
1,SpaceX,$100B,2012-12-01,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen...",2012,10
2,SHEIN,$100B,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China...",2018,10
3,Stripe,$95B,2014-01-23,Fintech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG",2014,4
4,Klarna,$46B,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita...",2011,6

In [15]:
companies.dtypes

Company                     object
Valuation                   object
Date Joined         datetime64[ns]
Industry                    object
City                        object
Country/Region              object
Continent                   object
Year Founded                 int64
Funding                     object
Select Investors            object
Year Joined                  int32
Years to Unicorn             int64
dtype: object

In [21]:
companies['Years to Unicorn'].describe(include= "all")

count    1074.000000
mean        7.000931
std         5.329672
min        -4.000000
25%         4.000000
50%         6.000000
75%         9.000000
max        98.000000
Name: Years to Unicorn, dtype: float64

In [28]:
companies['Years to Unicorn'].nsmallest(20)

714    -4
161     0
314     0
396     0
546     0
554     0
775     0
822     0
967     0
1001    0
26      1
33      1
52      1
78      1
94      1
102     1
127     1
151     1
226     1
238     1
Name: Years to Unicorn, dtype: int64

In [41]:
companies[companies['Years to Unicorn'] < 0]

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Year Joined,Years to Unicorn
714,Yidian Zixun,$1B,2017-10-17,Mobile & telecommunications,Beijing,China,Asia,2021,$151M,"Phoenix New Media, Tianjin Haihe Industry Fund",2017,-4

In [46]:
companies.loc[companies['Company'] == 'Yidian Zixun']['Year Founded'] = 2011

C:\Users\Adewole\AppData\Local\Temp\ipykernel_17940\570604803.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  companies.loc[companies['Company'] == 'Yidian Zixun']['Year Founded'] = 2011

In [49]:
companies.loc[714, 'Year Founded'] =2011

In [51]:
companies[companies['Years to Unicorn'] < 0]

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Year Joined,Years to Unicorn
714,Yidian Zixun,$1B,2017-10-17,Mobile & telecommunications,Beijing,China,Asia,2011,$151M,"Phoenix New Media, Tianjin Haihe Industry Fund",2017,-4

In [53]:
companies['Years to Unicorn'] = companies["Year Joined"] - companies["Year Founded"]

In [54]:
companies['Years to Unicorn'].describe()

count    1074.000000
mean        7.010242
std         5.319160
min         0.000000
25%         4.000000
50%         6.000000
75%         9.000000
max        98.000000
Name: Years to Unicorn, dtype: float64

In [55]:
industry_list = ['Artificial intelligence', 'Other','E-commerce & direct-to-consumer', 'Fintech',\
       'Internet software & services','Supply chain, logistics, & delivery', 'Consumer & retail',\
       'Data management & analytics', 'Edtech', 'Health', 'Hardware','Auto & transportation', \
        'Travel', 'Cybersecurity','Mobile & telecommunications']

In [56]:
industry_list

['Artificial intelligence',
 'Other',
 'E-commerce & direct-to-consumer',
 'Fintech',
 'Internet software & services',
 'Supply chain, logistics, & delivery',
 'Consumer & retail',
 'Data management & analytics',
 'Edtech',
 'Health',
 'Hardware',
 'Auto & transportation',
 'Travel',
 'Cybersecurity',
 'Mobile & telecommunications']

In [72]:
companies["Industry"].value_counts()

Industry
Fintech                                224
Internet software & services           205
E-commerce & direct-to-consumer        111
Health                                  74
Artificial intelligence                 73
Other                                   58
Supply chain, logistics, & delivery     57
Cybersecurity                           50
Data management & analytics             41
Mobile & telecommunications             38
Hardware                                34
Auto & transportation                   31
Edtech                                  28
Consumer & retail                       25
Travel                                  14
Artificial Intelligence                 11
Name: count, dtype: int64

In [70]:
set(companies['Industry']) - set(industry_list)

{'Artificial Intelligence'}

In [73]:
replacement_dict = {'Artificial Intelligence': 'Artificial intelligence',
                   'Data management and analytics': 'Data management & analytics',
                   'FinTech': 'Fintech'
                   }

In [74]:
companies['Industry'] = companies['Industry'].replace(replacement_dict)

In [75]:
set(companies["Industry"]) - set(industry_list)

set()

In [79]:
companies['Company'].duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1069    False
1070    False
1071    False
1072    False
1073    False
Name: Company, Length: 1074, dtype: bool

In [80]:
companies['Company'].drop_duplicates( keep='first')

0         Bytedance
1            SpaceX
2             SHEIN
3            Stripe
4            Klarna
           ...
1069       Zhaogang
1070    Zhuan Zhuan
1071       Zihaiguo
1072           Zopa
1073          Zwift
Name: Company, Length: 1073, dtype: object

In [86]:
def str_to_num(x): return int(x.strip('B$'))

In [87]:
companies['val_num'] = companies['Valuation'].apply(str_to_num)

In [88]:
companies['High Valuation'] = pd.qcut(
    companies['val_num'],
    2,
    labels = ['high', 'low'])

In [89]:
companies.head(20)

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Year Joined,Years to Unicorn,val_num,High Valuation
0,Bytedance,$180B,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S...",2017,5,180,low
1,SpaceX,$100B,2012-12-01,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen...",2012,10,100,low
2,SHEIN,$100B,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China...",2018,10,100,low
3,Stripe,$95B,2014-01-23,Fintech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG",2014,4,95,low
4,Klarna,$46B,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita...",2011,6,46,low
5,Canva,$40B,2018-01-08,Internet software & services,Surry Hills,Australia,Oceania,2012,$572M,"Sequoia Capital China, Blackbird Ventures, Mat...",2018,6,40,low
6,Checkout.com,$40B,2019-05-02,Fintech,London,United Kingdom,Europe,2012,$2B,"Tiger Global Management, Insight Partners, DST...",2019,7,40,low
7,Instacart,$39B,2014-12-30,"Supply chain, logistics, & delivery",San Francisco,United States,North America,2012,$3B,"Khosla Ventures, Kleiner Perkins Caufield & By...",2014,2,39,low
8,JUUL Labs,$38B,2017-12-20,Consumer & retail,San Francisco,United States,North America,2015,$14B,Tiger Global Management,2017,2,38,low
9,Databricks,$38B,2019-02-05,Data management & analytics,San Francisco,United States,North America,2013,$3B,"Andreessen Horowitz, New Enterprise Associates...",2019,6,38,low
10,Revolut,$33B,2018-04-26,Fintech,London,United Kingdom,Europe,2015,$2B,"index Ventures, DST Global, Ribbit Capital",2018,3,33,low
11,Epic Games,$32B,2018-10-26,Other,Cary,United States,North America,1991,$7B,"Tencent Holdings, KKR, Smash Ventures",2018,27,32,low
12,FTX,$32B,2021-07-20,Fintech,NaN,Bahamas,North America,2018,$2B,"Sequoia Capital, Thoma Bravo, Softbank",2021,3,32,low
13,Fanatics,$27B,2012-06-06,E-commerce & direct-to-consumer,Jacksonville,United States,North America,2002,$4B,"SoftBank Group, Andreessen Horowitz, Temasek H...",2012,10,27,low
14,Chime,$25B,2019-03-05,Fintech,San Francisco,United States,North America,2013,$2B,"Forerunner Ventures, Crosslink Capital, Homebrew",2019,6,25,low
15,BYJU's,$22B,2017-07-25,Edtech,Bengaluru,India,Asia,2008,$4B,"Tencent Holdings, Lightspeed India Partners, S...",2017,9,22,low
16,J&T Express,$20B,2021-04-07,"Supply chain, logistics, & delivery",Jakarta,Indonesia,Asia,2015,$5B,"Hillhouse Capital Management, Boyu Capital, Se...",2021,6,20,low
17,Xiaohongshu,$20B,2016-03-31,E-commerce & direct-to-consumer,Shanghai,China,Asia,2013,$918M,"GGV Capital, ZhenFund, Tencent",2016,3,20,low
18,Miro,$18B,2022-01-05,Internet software & services,San Francisco,United States,North America,2011,$476M,"Accel, AltaIR Capital, Technology Crossover Ve...",2022,11,18,low
19,Yuanfudao,$17B,2017-05-31,Edtech,Beijing,China,Asia,2012,$4B,"Tencent Holdings, Warbug Pincus, IDG Capital",2017,5,17,low

In [90]:
companies['Continent'].value_counts()

Continent
North America    589
Asia             310
Europe           143
South America     21
Oceania            8
Africa             3
Name: count, dtype: int64

In [91]:
continent_dict = {'North America': 1,
                  'Asia': 2,
                  'Europe': 3,
                  'South America': 4,
                  'Oceania': 5,
                  'Africa': 6
                 }
companies['Continent Number'] = companies['Continent'].replace(continent_dict)
companies.head()

C:\Users\Adewole\AppData\Local\Temp\ipykernel_17940\1654871584.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  companies['Continent Number'] = companies['Continent'].replace(continent_dict)

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Year Joined,Years to Unicorn,val_num,High Valuation,Continent Number
0,Bytedance,$180B,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S...",2017,5,180,low,2
1,SpaceX,$100B,2012-12-01,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen...",2012,10,100,low,1
2,SHEIN,$100B,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China...",2018,10,100,low,2
3,Stripe,$95B,2014-01-23,Fintech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG",2014,4,95,low,1
4,Klarna,$46B,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita...",2011,6,46,low,3

In [92]:
companies['Country/Region Numeric'] = companies['Country/Region'].astype('category').cat.codes

In [93]:
companies.head()

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Year Joined,Years to Unicorn,val_num,High Valuation,Continent Number,Country/Region Numeric
0,Bytedance,$180B,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S...",2017,5,180,low,2,9
1,SpaceX,$100B,2012-12-01,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen...",2012,10,100,low,1,44
2,SHEIN,$100B,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China...",2018,10,100,low,2,9
3,Stripe,$95B,2014-01-23,Fintech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG",2014,4,95,low,1,44
4,Klarna,$46B,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita...",2011,6,46,low,3,38

In [94]:
industry_encoded = pd.get_dummies(companies['Industry'])
companies = pd.concat([companies, industry_encoded],axis = 1)

companies.head()

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Year Joined,Years to Unicorn,val_num,High Valuation,Continent Number,Country/Region Numeric,Artificial intelligence,Auto & transportation,Consumer & retail,Cybersecurity,Data management & analytics,E-commerce & direct-to-consumer,Edtech,Fintech,Hardware,Health,Internet software & services,Mobile & telecommunications,Other,"Supply chain, logistics, & delivery",Travel
0,Bytedance,$180B,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S...",2017,5,180,low,2,9,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,SpaceX,$100B,2012-12-01,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen...",2012,10,100,low,1,44,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2,SHEIN,$100B,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China...",2018,10,100,low,2,9,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
3,Stripe,$95B,2014-01-23,Fintech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG",2014,4,95,low,1,44,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
4,Klarna,$46B,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita...",2011,6,46,low,3,38,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False